# Generated by Django 5.2.4 on 2026-07-13 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_url', models.URLField(blank=True, max_length=500)),
                ('position', models.CharField(choices=[('top_banner', 'Top Banner'), ('sidebar', 'Sidebar'), ('between_articles', 'Between Articles'), ('footer_banner', 'Footer Banner')], default='between_articles', max_length=30)),
                ('image', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
